/** @format */

var car = [
  {
    name: 'Nissan Magnite XE',
    drive: 'Manual',
    fuel: 'Petrol',
    space: '5 Seats',
    reating: '4.9 (12)',
    driven: '22,821kms driven',
    age: '10',
    price: '₹3,750',
    type: 'SUV',
  },
  {
    name: 'Ford Ecosport ',
    drive: 'Manual',
    fuel: 'Petrol',
    space: '5 Seats',
    reating: '4.87 (9)',
    driven: '52,677 kms driven',
    age: '12',
    price: '₹4,958',
    type: 'SUV',
  },
  {
    name: 'KIA Sonet ',
    drive: 'Manual',
    fuel: 'Petrol',
    space: '5 Seats',
    reating: '4.82 (6)',
    driven: '14,844 kms driven',
    age: '12',
    price: '₹5,476',
    type: 'SUV',
  },
  {
    name: 'Renault Triber',
    drive: 'Manual',
    fuel: 'Petrol',
    space: '7 Seats',
    reating: '5.0 (6)',
    driven: '16,578 kms driven',
    age: '12',
    price: '₹3,679',
    type: 'SUV',
  },
  {
    name: 'Renault Triber',
    drive: 'Manual',
    fuel: 'Petrol',
    space: '7 Seats',
    reating: '4.79 (65)',
    driven: '39,274 kms driven',
    age: '20',
    price: '₹4,567',
    type: 'SUV',
  },
  {
    name: 'Renault Lodgy ',
    drive: 'Manual',
    fuel: 'Diesel',
    space: '7 Seats',
    reating: '4.69 (24)',
    driven: '54,281 kms driven',
    age: '20',
    price: '₹5,649',
    type: 'SUV',
  },
  {
    name: 'RTriber  ',
    drive: 'Manual',
    fuel: 'Diesel',
    space: '5 Seats',
    reating: '4.41 (94)',
    driven: '42,963 kms driven',
    age: '20',
    price: '₹4,560',
    type: 'SUV',
  },
  {
    name: 'Nexon  ',
    drive: 'Manual',
    fuel: 'Petrol',
    space: '5 Seats',
    reating: '4.76 (49)',
    driven: '73,740 kms driven',
    age: '20',
    price: '₹3,848',
    type: 'SUV',
  },
  {
    name: 'Hyundai Venue ',
    drive: 'Manual',
    fuel: 'Petrol',
    space: '5 Seats',
    reating: '4.3 (12)',
    driven: '50,000 kms driven',
    age: '20',
    price: '₹4,344',
    type: 'SUV',
  },
  {
    name: 'Vitara Brezza ',
    drive: 'Manual',
    fuel: 'Petrol',
    space: '5 Seats',
    reating: '5.0 ',
    driven: '368 kms driven',
    age: '20',
    price: '₹4,321',
    type: 'SUV',
  },
  {
    name: 'Maruti Dzire ',
    drive: 'Manual',
    fuel: 'Petrol',
    space: '5 Seats',
    reating: '4.97 (52) ',
    driven: '17,584 kms driven ',
    age: '20',
    price: '₹4,918',
    type: 'Sedan',
  },
  {
    name: 'Maruti Swift ',
    drive: 'Manual',
    fuel: 'Petrol',
    space: '5 Seats',
    reating: '4.81 (37) ',
    driven: ' 33,520 kms driven ',
    age: '20',
    price: '₹3,948',
    type: 'Sedan',
  },
  {
    name: 'Honda Amaze ',
    drive: 'Manual',
    fuel: 'Petrol',
    space: '5 Seats',
    reating: '4.87 (42) ',
    driven: ' 28,010 kms driven',
    age: '20',
    price: '₹4,007',
    type: 'Sedan',
  },
  {
    name: 'Hyundai Xcent',
    drive: 'Manual',
    fuel: 'Petrol',
    space: '5 Seats',
    reating: '4.87 (64) ',
    driven: '  67,067 kms driven',
    age: '20',
    price: '₹3,254',
    type: 'Sedan',
  },
  {
    name: 'Hyundai Elantra',
    drive: 'Manual',
    fuel: 'Diesel',
    space: '5 Seats',
    reating: '4.87 (64) ',
    driven: '  47,783 kms driven',
    age: '20',
    price: '₹5,694',
    type: 'Sedan',
  },
  {
    name: 'Maruti Dzire ',
    drive: 'Manual',
    fuel: 'Petrol',
    space: '5 Seats',
    reating: '4.0 (52) ',
    driven: '17,084 kms driven ',
    age: '20',
    price: '₹3,008',
    type: 'Sedan',
  },
  {
    name: 'Hyundai Elantra',
    drive: 'Manual',
    fuel: 'Diesel',
    space: '5 Seats',
    reating: '3.87 (64) ',
    driven: '  9,783 kms driven',
    age: '12',
    price: '₹3,694',
    type: 'Sedan',
  },
  {
    name: 'Hyundai Xcent',
    drive: 'Manual',
    fuel: 'Petrol',
    space: '5 Seats',
    reating: '2.87 (64) ',
    driven: '  97,067 kms driven',
    age: '20',
    price: '₹3,254',
    type: 'Sedan',
  },
];
